#!/usr/bin/expect

set timeout -1
set port [lindex $argv 0]
spawn bash
send "bash ssr.sh\r"
expect {
"*取消*" { send "1\r" ; sleep 1 ; exp_continue }
"*请输入数字*" { send "7\r" ; sleep 1 ; exp_continue }
"*2333*" { send "$port\r" }
}
expect "*======*"
send "firewall-cmd --permanent --add-port=$port/tcp\r"
expect "success"
send "firewall-cmd --reload ; exit ; logout\r"
interact
